"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { MdsBadge } from "@/components/shared/mds-badge";
import { ChainBadge } from "@/components/shared/chain-badge";
import { formatUSD, formatNumber } from "@/lib/utils";
import { saveProposal, type MigrationProposal } from "@/lib/types/proposals";
import { FileText, Copy, Check } from "lucide-react";
import type { TokenDetail } from "@/lib/data";

interface ProposalFormProps {
  token: TokenDetail;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ProposalForm({ token, open, onOpenChange }: ProposalFormProps) {
  const [step, setStep] = useState<"form" | "preview">("form");
  const [whyThisToken, setWhyThisToken] = useState(
    `${token.symbol} has a Migration Demand Score of ${token.mds.totalScore}, indicating ${token.mds.totalScore >= 70 ? "strong" : "moderate"} demand from Solana users. Key signals include ${formatUSD(token.bridgeVolume7d)} in weekly bridge outflows and ${token.socialData.demandMentions} demand-specific social mentions.`
  );
  const [strategy, setStrategy] = useState(
    `Migrate ${token.symbol} via Sunrise NTT with day-one liquidity on Jupiter. Target DeFi integrations on Kamino and MarginFi within week one.`
  );
  const [copied, setCopied] = useState(false);

  const handleGenerate = () => {
    const proposal: MigrationProposal = {
      id: `${token.id}-${Date.now()}`,
      tokenId: token.id,
      tokenSymbol: token.symbol,
      tokenName: token.name,
      mdsScore: token.mds.totalScore,
      whyThisToken,
      proposedStrategy: strategy,
      createdAt: new Date().toISOString(),
      marketCap: token.marketCap,
      bridgeVolume7d: token.bridgeVolume7d,
      demandMentions: token.socialData.demandMentions,
      walletOverlap: token.walletOverlap.overlapPercentage,
    };
    saveProposal(proposal);
    setStep("preview");
  };

  const proposalText = `
MIGRATION PROPOSAL: ${token.symbol} (${token.name})
${"=".repeat(50)}

Migration Demand Score: ${token.mds.totalScore}/100 (${token.mds.trend})
Origin Chain: ${token.originChain}
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
${"-".repeat(30)}
${whyThisToken}

MARKET DATA
${"-".repeat(30)}
Market Cap:      ${formatUSD(token.marketCap)}
24h Volume:      ${formatUSD(token.volume24h)}
TVL:             ${formatUSD(token.tvl)}
Holders:         ${formatNumber(token.holders)}
7d Change:       ${token.change7d > 0 ? "+" : ""}${token.change7d}%

DEMAND EVIDENCE
${"-".repeat(30)}
Bridge Outflow (7d):    ${formatUSD(token.bridgeVolume7d)}
Search Intent Score:    ${token.mds.breakdown.searchIntent.normalized}/100
Social Demand Mentions: ${token.socialData.demandMentions}
Wallet Overlap:         ${token.walletOverlap.overlapPercentage}% (${formatNumber(token.walletOverlap.solanaWallets)} Solana wallets)
Sentiment:              ${(token.socialData.sentiment * 100).toFixed(0)}% positive

PROPOSED STRATEGY
${"-".repeat(30)}
${strategy}

READINESS ASSESSMENT
${"-".repeat(30)}
Bridge Support:    ${token.mds.breakdown.bridgeOutflow.normalized > 50 ? "Ready" : "Needs evaluation"}
Team Activity:     Active
DeFi Potential:    ${token.tvl > 500_000_000 ? "High" : "Moderate"}
Community Size:    ${formatNumber(token.holders)} holders

---
Generated by Tideshift — tideshift.app
Powered by Sunrise
`.trim();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(proposalText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClose = (value: boolean) => {
    if (!value) {
      setStep("form");
      setCopied(false);
    }
    onOpenChange(value);
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl glass-card border-white/10">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            <FileText className="h-5 w-5 text-primary" />
            {step === "form" ? "Generate Migration Proposal" : "Proposal Preview"}
          </DialogTitle>
        </DialogHeader>

        {step === "form" ? (
          <div className="space-y-5">
            {/* Token Summary */}
            <div className="flex items-center gap-3 p-3 rounded-lg bg-white/[0.03]">
              <div className="h-10 w-10 rounded-full bg-white/10 flex items-center justify-center font-bold">
                {token.symbol.slice(0, 2)}
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium">{token.symbol}</span>
                  <ChainBadge chainId={token.originChain} size="sm" />
                </div>
                <p className="text-xs text-muted-foreground">{token.name}</p>
              </div>
              <MdsBadge score={token.mds.totalScore} size="md" />
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-4 gap-3">
              {[
                { label: "Market Cap", value: formatUSD(token.marketCap) },
                { label: "Bridge Vol.", value: formatUSD(token.bridgeVolume7d) },
                { label: "Demand Mentions", value: `${token.socialData.demandMentions}` },
                { label: "Wallet Overlap", value: `${token.walletOverlap.overlapPercentage}%` },
              ].map((stat) => (
                <div key={stat.label} className="text-center p-2 rounded-lg bg-white/[0.02]">
                  <p className="text-[10px] text-muted-foreground">{stat.label}</p>
                  <p className="text-sm font-mono font-bold">{stat.value}</p>
                </div>
              ))}
            </div>

            {/* Form Fields */}
            <div className="space-y-3">
              <div>
                <label className="text-sm font-medium mb-1.5 block">
                  Why this token?
                </label>
                <Textarea
                  value={whyThisToken}
                  onChange={(e) => setWhyThisToken(e.target.value)}
                  rows={3}
                  className="bg-white/5 border-white/10 text-sm"
                />
              </div>
              <div>
                <label className="text-sm font-medium mb-1.5 block">
                  Proposed strategy
                </label>
                <Textarea
                  value={strategy}
                  onChange={(e) => setStrategy(e.target.value)}
                  rows={2}
                  className="bg-white/5 border-white/10 text-sm"
                />
              </div>
            </div>

            <Button
              onClick={handleGenerate}
              className="w-full bg-gradient-to-r from-purple-500 to-cyan-500 text-white hover:opacity-90"
            >
              Generate Proposal
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex gap-2">
              <Badge variant="outline" className="border-emerald-500/30 text-emerald-400 text-xs">
                Saved to proposals
              </Badge>
            </div>

            <pre className="p-4 rounded-lg bg-black/30 text-xs font-mono whitespace-pre-wrap max-h-96 overflow-y-auto text-muted-foreground leading-relaxed">
              {proposalText}
            </pre>

            <div className="flex gap-2">
              <Button onClick={handleCopy} variant="outline" className="flex-1">
                {copied ? (
                  <Check className="h-4 w-4 mr-2 text-emerald-400" />
                ) : (
                  <Copy className="h-4 w-4 mr-2" />
                )}
                {copied ? "Copied!" : "Copy to Clipboard"}
              </Button>
              <Button
                asChild
                className="flex-1 bg-gradient-to-r from-purple-500 to-cyan-500 text-white hover:opacity-90"
              >
                <a
                  href="https://sunrisedefi.com/apply"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Submit to Sunrise
                </a>
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
